//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleImageResizer.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleImageResizer.Localize.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist.
        ///However, it will be created when images are resized..
        /// </summary>
        public static string ButtonDestinationNotFoundMessage {
            get {
                return ResourceManager.GetString("ButtonDestinationNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Does Not Exist.
        /// </summary>
        public static string ButtonDestinationNotFoundTitle {
            get {
                return ResourceManager.GetString("ButtonDestinationNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string CommandBatch {
            get {
                return ResourceManager.GetString("CommandBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CommandCancel {
            get {
                return ResourceManager.GetString("CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CommandClear {
            get {
                return ResourceManager.GetString("CommandClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string CommandDestination {
            get {
                return ResourceManager.GetString("CommandDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string CommandProcess {
            get {
                return ResourceManager.GetString("CommandProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string CommandSelect {
            get {
                return ResourceManager.GetString("CommandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string CommandSettings {
            get {
                return ResourceManager.GetString("CommandSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the destination directory for your resized images..
        /// </summary>
        public static string DestinationDialogTitle {
            get {
                return ResourceManager.GetString("DestinationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop your images here!.
        /// </summary>
        public static string DragAndDrop {
            get {
                return ResourceManager.GetString("DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmp.
        /// </summary>
        public static string ImageTypeBitmap {
            get {
                return ResourceManager.GetString("ImageTypeBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gif.
        /// </summary>
        public static string ImageTypeGif {
            get {
                return ResourceManager.GetString("ImageTypeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jfif.
        /// </summary>
        public static string ImageTypeJfif {
            get {
                return ResourceManager.GetString("ImageTypeJfif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpg.
        /// </summary>
        public static string ImageTypeJpg {
            get {
                return ResourceManager.GetString("ImageTypeJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string ImageTypeOriginal {
            get {
                return ResourceManager.GetString("ImageTypeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        public static string ImageTypePng {
            get {
                return ResourceManager.GetString("ImageTypePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tif.
        /// </summary>
        public static string ImageTypeTif {
            get {
                return ResourceManager.GetString("ImageTypeTif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MenuLanguageEnglish {
            get {
                return ResourceManager.GetString("MenuLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Log.
        /// </summary>
        public static string MenuProcessingLog {
            get {
                return ResourceManager.GetString("MenuProcessingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time:.
        /// </summary>
        public static string ProcessingCompleteMsgElapsedTime {
            get {
                return ResourceManager.GetString("ProcessingCompleteMsgElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images processed:.
        /// </summary>
        public static string ProcessingCompleteMsgImagesProcessed {
            get {
                return ResourceManager.GetString("ProcessingCompleteMsgImagesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Complete.
        /// </summary>
        public static string ProcessingCompleteMsgTitle {
            get {
                return ResourceManager.GetString("ProcessingCompleteMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ScalingOptionHeight {
            get {
                return ResourceManager.GetString("ScalingOptionHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ScalingOptionNone {
            get {
                return ResourceManager.GetString("ScalingOptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ScalingOptionWidth {
            get {
                return ResourceManager.GetString("ScalingOptionWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Images | *.bmp; *.gif; *.jfif; *.jpg; *.png; *.tif&quot;.
        /// </summary>
        public static string SelectImagesSupportedTypes {
            get {
                return ResourceManager.GetString("SelectImagesSupportedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add numeric suffix.
        /// </summary>
        public static string SettingsAddNumeric {
            get {
                return ResourceManager.GetString("SettingsAddNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Output Mode.
        /// </summary>
        public static string SettingsAdvanced {
            get {
                return ResourceManager.GetString("SettingsAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear images on completion.
        /// </summary>
        public static string SettingsClearImages {
            get {
                return ResourceManager.GetString("SettingsClearImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG quality (30-100).
        /// </summary>
        public static string SettingsJpgQuality {
            get {
                return ResourceManager.GetString("SettingsJpgQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default value..
        /// </summary>
        public static string SettingsJpgQualityResetTooltip {
            get {
                return ResourceManager.GetString("SettingsJpgQualityResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SettingsOptions {
            get {
                return ResourceManager.GetString("SettingsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing.
        /// </summary>
        public static string SettingsOverwrite {
            get {
                return ResourceManager.GetString("SettingsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string SettingsPercentage {
            get {
                return ResourceManager.GetString("SettingsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SettingsSaveAs {
            get {
                return ResourceManager.GetString("SettingsSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show message box on completion.
        /// </summary>
        public static string SettingsShowMsg {
            get {
                return ResourceManager.GetString("SettingsShowMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        public static string SettingsUseAbsolute {
            get {
                return ResourceManager.GetString("SettingsUseAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all available processors.
        /// </summary>
        public static string SettingsUseAllProcessors {
            get {
                return ResourceManager.GetString("SettingsUseAllProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect.
        /// </summary>
        public static string SettingsUseAspect {
            get {
                return ResourceManager.GetString("SettingsUseAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use simple resizing.
        /// </summary>
        public static string SettingsUseSimple {
            get {
                return ResourceManager.GetString("SettingsUseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string SimpleImageResizeLarge {
            get {
                return ResourceManager.GetString("SimpleImageResizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string SimpleImageResizeMedium {
            get {
                return ResourceManager.GetString("SimpleImageResizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string SimpleImageResizeSmall {
            get {
                return ResourceManager.GetString("SimpleImageResizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SimpleImageResizeUnknown {
            get {
                return ResourceManager.GetString("SimpleImageResizeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Output Mode in use..
        /// </summary>
        public static string StatusBarAdvancedInUse {
            get {
                return ResourceManager.GetString("StatusBarAdvancedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be set between 30 and 100..
        /// </summary>
        public static string ValidateJpg {
            get {
                return ResourceManager.GetString("ValidateJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be set between 1 and 99..
        /// </summary>
        public static string ValidatePercentage {
            get {
                return ResourceManager.GetString("ValidatePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be set between 1 and 100000..
        /// </summary>
        public static string ValidateValue1and100000 {
            get {
                return ResourceManager.GetString("ValidateValue1and100000", resourceCulture);
            }
        }
    }
}
